site_name: FletWebviewAll
site_url: https://zaim-tech.github.io/flet-webview-all/
repo_url: https://github.com/zaim-tech/flet-webview-all
repo_name: zaim-tech/flet-webview-all
site_description: Cross-platform WebView control for Flet

nav:
  - Home: index.md
  - Complete API guide: FletWebviewAll.md
  - Examples: examples.md
  - Permissions: permissions.md
  - Advanced APIs: advanced.md

theme:
  name: "material"
  features:
    - search.suggest    
    - search.highlight  
    - search.share      

plugins:
  - search            
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
