[project]
name = "flet-webview-all"
version = "0.1.7"
description = "FletWebviewAll control for Flet"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet contributors", email = "you@example.com" }
]
dependencies = [
    "flet>=0.86.5",
]

[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]"
]

[project.urls]
Homepage = "https://github.com/zaim-tech/flet-webview-all"
Documentation = "https://github.com/zaim-tech/flet-webview-all"
Repository = "https://github.com/zaim-tech/flet-webview-all"
Issues = "https://github.com/zaim-tech/flet-webview-all/issues"

[tool.setuptools.package-data]
"flutter.flet_webview_all" = [
    "pubspec.yaml",
    "pubspec.lock",
    "lib/*.dart",
    "lib/**/*.dart",
]

[tool.setuptools]
license-files = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


